# Generated by Django 4.2.7 on 2023-11-21 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_store', '0008_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billdetails',
            name='bill_id',
        ),
        migrations.RemoveField(
            model_name='billdetails',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='BillDetails',
        ),
    ]
