# Generated by Django 4.2.7 on 2023-11-21 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_store', '0010_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hardware_store.pedido'),
        ),
    ]
