# Generated by Django 4.2.7 on 2023-11-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_store', '0011_cartitem_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='direccion',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='numero_de_casa',
            new_name='housenumber',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='telefono',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='hora_recogida',
            new_name='pickup_time',
        ),
    ]
