# Generated by Django 4.2.7 on 2023-11-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_store', '0012_rename_direccion_pedido_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('ENTREGADA', 'Entregada')], default='PENDIENTE', max_length=20),
        ),
    ]
